# Generated by Django 5.2.2 on 2025-09-22 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_order_email_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petshop.orderitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('В работе', 'В работе'), ('Завершён', 'Завершён'), ('Получен', 'Получен')], default='В обработке', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
