# Generated by Django 5.2.2 on 2025-09-24 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0006_remove_review_order_item_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersByBrand',
            fields=[
                ('brand_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_orders', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'petshop_orders_by_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersByCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('total_orders', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'petshop_orders_by_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersByMonth',
            fields=[
                ('month', models.DateField(primary_key=True, serialize=False)),
                ('total_orders', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'petshop_orders_by_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('row_id', models.BigIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление')], max_length=10)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
    ]
