# Generated by Django 5.2.2 on 2025-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0007_ordersbybrand_ordersbycategory_ordersbymonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление')], max_length=20),
        ),
    ]
