# Generated by Django 5.2.2 on 2025-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0010_alter_agecategory_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_format',
            field=models.CharField(default='%d.%m.%Y', help_text='Например: %d.%m.%Y или %Y.%m.%d', max_length=20, verbose_name='Формат даты'),
        ),
    ]
