# Generated by Django 5.2.2 on 2025-10-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0011_alter_userprofile_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_format',
            field=models.CharField(default='%d.%m.%Y', max_length=20, verbose_name='Формат даты'),
        ),
    ]
